const projects = [
    {
        id: 1,
        title: "Project 1",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/1",
        github: 'https://github.com/',
    },
    {
        id: 2,
        title: "Project 2",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/2",
        github: 'https://github.com/',    },
    {
        id: 3,
        title: "Project 3",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/3",
        github: 'https://github.com/',    },
    {
        id: 4,
        title: "Project 4",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/4",
        github: 'https://github.com/',    },
    {
        id: 5,
        title: "Project 5",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/5",
        github: 'https://github.com/',    },
    {
        id: 6,
        title: "Project 6",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/6",
        github: 'https://github.com/',    },
    {
        id: 7,
        title: "Project 7",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/7",
        github: 'https://github.com/',    },
    {
        id: 8,
        title: "Project 8",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/8",
        github: 'https://github.com/',    },
    {
        id: 9,
        title: "Project 9",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/9",
        github: 'https://github.com/',    },
];

export default projects;