const projects = [
    {
        id: 1,
        title: "A simple web page",
        description: "An intro to MERN",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/1",
        github: 'https://github.com/WSPineda/CS3750-Portfolio/tree/main/project1',
    },
    {
        id: 2,
        title: "Node/Express website",
        description: "Learning E and N of MERN",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/2",
        github: 'https://github.com/WSPineda/CS3750-Portfolio/tree/main/project2',    },
    {
        id: 3,
        title: "Node, Express, Mongo, and RESTful API",
        description: "",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/3",
        github: 'https://github.com/WSPineda/CS3750-Portfolio/tree/main/project3',    },
    {
        id: 4,
        title: "MERN and Sessions",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/4",
        github: 'https://github.com/WSPineda/CS3750-Portfolio/tree/main/project4',    },
    {
        id: 5,
        title: "Hangman Game",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/5",
        github: 'https://github.com/WSPineda/CS3750-Portfolio/tree/main/project5',    },
    {
        id: 6,
        title: "Banking Application",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/project_icon.png",
        link: "/project/6",
        github: 'https://github.com/WSPineda/CS3750-Portfolio/tree/main/project6',    },

];

export default projects;